#!/bin/bash
### entering chroot
/usr/sbin/chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin     \
    /bin/bash --login -c "\
sh chroot_setup3
sh chroot_setup4
