#!/bin/bash

echo "Select LFS partition"
ls /dev/sd*
read partition
mkfs -v -t ext4 /dev/$partition

echo "Select LFS swap partition"
ls /dev/sd*
read swapp
mkswqp /dev/$swapp

LFS=/mnt/lfs

mkdir -pv $LFS
mount -v -t ext4 /dev/$partition $LFS
/sbin/swapon -v /dev/$swapp

