#!/bin/bash
cd $LFS/sources/kmod-30

./configure --prefix=/usr          \
            --sysconfdir=/etc      \
            --with-openssl         \
            --with-xz              \
            --with-zstd            \
            --with-zlib

make -j4

make install

for target in depmod insmod modinfo modprobe rmmod; do
  ln -sfv ../bin/kmod /usr/sbin/$target
done

ln -sfv kmod /usr/bin/lsmod

if [ depmod ]
then
echo " kmod is installed" >> ../make_all/install.log
else
echo " kmod not install" >> ../make_all/install.log
fi
