#!/bin/bash
cd $LFS/sources/mpc

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.2.1

make
make html

#make check

make install
make install-html

echo "mpc config complete" >> ../../make_all/install.log
