#!/bin/bash
cd $LFS/sources/mpfr

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-4.1.1

make
make html

#make check

make install
make install-html

echo "mpfr config complete"  >> ../../make_all/install.log
