#!/bin/bash
cd $LFS/sources/systemd-252

sed -i -e 's/GROUP="render"/GROUP="video"/' \
       -e 's/GROUP="sgx", //' rules.d/50-udev-default.rules.in

mkdir -p build
cd       build

meson --prefix=/usr                 \
      --buildtype=release           \
      -Ddefault-dnssec=no           \
      -Dfirstboot=false             \
      -Dinstall-tests=false         \
      -Dldconfig=false              \
      -Dsysusers=false              \
      -Drpmmacrosdir=no             \
      -Dhomed=false                 \
      -Duserdb=false                \
      -Dman=false                   \
      -Dmode=release                \
      -Dpamconfdir=no               \
      -Ddocdir=/usr/share/doc/systemd-252 \
      ..

ninja

ninja install

tar -xf ../../systemd-man-pages-252.tar.xz --strip-components=1 -C /usr/share/man

systemd-machine-id-setup

systemctl preset-all

systemctl disable systemd-sysupdate{,-reboot}

if [ busctl ]
then
echo "systemd is installed" >> ../../make_all/install.log
else
echo "systemd not install" >> ../../make_all/install.log
fi
