#!/bin/bash
sh /root/env
cd $LFS/sources/binutils-2.39
mkdir build
cd build

../configure --prefix=$LFS/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --enable-gprofng=no \
             --disable-werror

make -j3
make install
make distclean
