#!/bin/bash
a=$(pwd)
sh /$a/env
cd $LFS/sources/binutils-2.39	


sed '6009s/$add_dir//' -i ltmain.sh

mkdir -v build
cd       build

../configure                   \
    --prefix=/usr              \
    --build=$(../config.guess) \
    --host=$LFS_TGT            \
    --disable-nls              \
    --enable-shared            \
    --enable-gprofng=no        \
    --disable-werror           \
    --enable-64-bit-bfd

make -j3
make DESTDIR=$LFS install

make distclean
rm -v $LFS/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.{a,la}
echo "binutils_pass2_finish" >> $/LFS/sources/install.log

