#!/bin/bash
a=$(pwd)
sh /$a/env

cd $LFS/sources/findutils-4.9.0


./configure --prefix=/usr                   \
            --localstatedir=/var/lib/locate \
            --host=$LFS_TGT                 \
            --build=$(build-aux/config.guess)

make -j3

make DESTDIR=$LFS install

make distclean

echo "findutils_finish" >> $/LFS/sources/install.log


