#!/bin/bash
a=$(pwd)
sh /$a/env

cd $LFS/sources/linux-6.0.11

make mrproper
make headers
find usr/include -type f ! -name '*.h' -delete
cp -rv usr/include $LFS/usr

echo "linux_finish" >> $/LFS/sources/install.log

