#!/bin/bash
#a=$(pwd)
#sh /$a/env

cd $LFS/sources/m4-1.4.19

./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)

make -j3

make DESTDIR=$LFS install

make distclean

echo "m4_pass_1_finish" >> $LFS/sources/install.log

