#!/bin/bash
sh /home/steven/Desktop/file/env
cd $LFS/sources/gawk-5.2.1

sed -i 's/extras//' Makefile.in

./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)

make -j3

make DESTDIR=$LFS install

make distclean

echo "gawk_pass_1_finish" >> $LFS/sources/install.log

