#!/bin/bash 
su - lfs -c "\
su root -c "\
sh binutils-2.39_pass1
sh gcc-12.2.0_pass1
sh linux_API_header
sh glibc-2.36
sh libstdc++
sh m4-1.4.19
sh ncurses-6.3
sh bash-5.2.9	
sh coreutils-9.1	
sh file-5.43
sh findutils-4.9.0
sh gawk-5.2.1
sh grep-3.8	
sh gzip-1.12
sh make-4.4
sh patch-2.7.6
sh sed-4.9
sh tar-1.34
sh xz-5.2.9
sh binutils-2.39_pass2
sh gcc-12.2.0_pass2 \
""

