#!/bin/bash
#a=$(pwd)
#sh /$a/env
cd $LFS/sources/sed-4.9


./configure --prefix=/usr   \
            --host=$LFS_TGT


make -j3
make DESTDIR=$LFS install

make distclean

echo "sed_pass1_finish" >> $LFS/sources/install.log

